# Generated by Django 4.1.5 on 2023-01-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_category_alter_review_review_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review", name="review", field=models.TextField(),
        ),
    ]
