# Generated by Django 4.1.5 on 2023-01-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_review_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="clarusway.png", null=True, upload_to="product/"
            ),
        ),
    ]
